### ISSUE TITLE
Dead link to the Python tutorial in README 

### ISSUE THREAD

**Issue by oooic** [coudertlab/CrystalNets.jl#17]
I would like to draw your attention to an issue I encountered when attempting to access the Python tutorial of the CrystalNets.jl documentation from the README. Specifically, I was using the link: `https://molsim.info/CrystalNets.jl/dev/python`. However, I regret to inform you that this link redirects to a GitHub 404 page, indicating that the page is not available.

I was able to successfully access the tutorial using an alternative link: `https://coudertlab.github.io/CrystalNets.jl/dev/python`. Given that this link led me to the desired content, it suggests that the latter might be the correct and functional link.

To improve the user experience and ensure seamless access to the CrystalNets.jl documentation, I kindly request that you investigate the issue with the initial link (`https://molsim.info/CrystalNets.jl/dev/python`) and consider rectifying it. This would prevent users from encountering the 404 page and instead allow them to easily access the tutorial they are looking for.

Thank you for your prompt attention to this matter, and I appreciate your commitment to maintaining the CrystalNets.jl project.

**Comment by Liozou** [comment]
Thank you very much for reporting this! The `molsim` URL is indeed not functional anymore, I will switch the links to the original github page, exactly as you suggested. I just updated the links of the website (https://progs.coudert.name/topology) as well.

Please don't hesitate to let me know if you encounter any related issue, or any other while using CrystalNets.jl.
