### ISSUE TITLE
consider adding a CITATION.cff

### ISSUE THREAD

**Issue by egonw** [coudertlab/CrystalNets.jl#9]
Hi, I just noticed your article under review with SciPost Chemistry. Please consider adding a CITATION.cff, see https://citation-file-format.github.io/ (link to the preprint now, to the full print later, perhaps).

**Comment by Liozou** [comment]
Thank you for the suggestion! This was added in commit https://github.com/coudertlab/CrystalNets.jl/commit/e428d6123142551253b769a79a77d3a254a73dd3.
